image: python:3.6-alpine
stages:
  - test
  - coverage
test_with_pytest:
  stage: test
  script:
    - pip install pytest
    - pip install pytest-cov
    - python -m pytest --cov=./ --cov-report=xml
  artifacts:
    paths:
      - coverage.xml
coverage_with_codecov:
  stage: coverage
  script:
    - pip install codecov
    - codecov -t "$CODECOV_TOKEN"
